baseURL = 'https://ralfwirdemann.de/'
languageCode = 'en-us'
title = 'Ralf Wirdemann'
# theme = 'PaperMod'
theme = 'hugo-theme-m10c'

[params]
  author = 'Ralf Wirdemann'
  description = ' '
  menu_item_separator = " - "
  avatar = "/avatar.png"
  [[params.social]]
    icon = "brand-github"
    name = "My Github"
    url = "https://github.com/rwirdemann"

  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://de.linkedin.com/in/ralfwirdemann"

[languages.en]
languageName = "English"
weight = 1

[menu]
  [[languages.en.menu.main]]
  name = "About"
  url = "/"
  weight = 5
  [[languages.en.menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 5
  [[languages.en.menu.main]]
  name = "Books"
  url = "/books/"
  weight = 5
  [[languages.en.menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 5

